use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum Error {
    MatchNotFound = 1,
    AlreadyFunded = 2,
    NotFunded = 3,
    Unauthorized = 4,
    InvalidState = 5,
    AlreadyExists = 6,
    AlreadyInitialized = 7,
    Overflow = 8,
    ContractPaused = 9,
    InvalidAmount = 10,
    MatchCancelled = 11,
    MatchCompleted = 12,
    DuplicateGameId = 13,
    MatchNotExpired = 14,
    InvalidGameId = 15,
    InvalidPlayers = 16,
    TokenNotAllowed = 17,
    InvalidAddress = 18,
    MatchAlreadyActive = 19,
    InvalidTimeout = 20,
    SnapshotNotFound = 21,
    VestingNotExpired = 22,
    AlreadyClaimed = 23,
    DisputeNotFound = 24,
    PendingResultNotFound = 25,
    DisputeAlreadyResolved = 26,
    VotingPeriodElapsed = 27,
    AlreadyVoted = 28,
    NotStaker = 29,
    VotingPeriodNotElapsed = 30,
    MatchNotInPendingResult = 31,
    DisputePeriodNotElapsed = 32,
    DisputeAlreadyRaised = 33,
    InvalidEvidenceHash = 34,
    TierStakeNotAllowed = 35,
    NotInitialized = 36,
    InvalidPauseState = 37,
    InvalidConversionRate = 38,
    ConversionRateOutOfBounds = 39,
    ConversionRateStalePriceSource = 40,
}
